library(parsnip)
library(glmnet)
library(tune)
library(dplyr)
library(elo)
library(tidyr)
library(rvest)
library(xml2)
library(httr)
library(logger)

win_model <- readRDS("/app/nfl_win_api/R/win_model_logistic_reg.rds")